let make= () => {<View style={viewStyle(    ~flex = 1.0, 
    (), 
)}><View style={viewStyle(    ~paddingBottom = 4.->dp, 
    ~paddingLeft = 12.->dp, 
    ~paddingRight = 4.->dp, 
    ~paddingTop = 4.->dp, 
    ~paddingVertical = 4.->dp, 
    ~paddingHorizontal = 12.->dp, 
    ~backgroundColor = "#ffffff", 
    ~opacity = 1, 
    ~borderBottomWidth = 1.0, 
    ~borderLeftWidth = 1.0, 
    ~borderRightWidth = 1.0, 
    ~borderTopWidth = 1.0, 
    ~borderRadius = 32.0, 
    ~flexDirection = #row, 
    ~flex = 1.0, 
    (), 
)}><Text style={viewStyle(    ~includeFontPadding = true, 
    ~backgroundColor = "#6e7381", 
    ~opacity = 1, 
    (), 
)}>
{OTP}
</Text><View style={viewStyle(        ~paddingBottom = 8.->dp, 
        ~paddingLeft = 12.->dp, 
        ~paddingRight = 12.->dp, 
        ~paddingTop = 8.->dp, 
        ~paddingVertical = 8.->dp, 
        ~paddingHorizontal = 12.->dp, 
        ~backgroundColor = "#f5f5f7", 
        ~opacity = 1, 
        ~borderBottomWidth = 1.0, 
        ~borderLeftWidth = 1.0, 
        ~borderRightWidth = 1.0, 
        ~borderTopWidth = 1.0, 
        ~borderRadius = 16.0, 
        ~flexDirection = #row, 
        (), 
)}><Text style={viewStyle(        ~includeFontPadding = true, 
        ~backgroundColor = "#2d303b", 
        ~opacity = 1, 
        (), 
)}>
{7891}
</Text></View></View></View>
}